Repository NVE/actinia_modules_nve, pull requests merged in 2024-01, with the labels that each got.

#27 added option for downloading selection of scenes
  src/imagery/i.asf.download/i.asf.download.py
Labels: enhancement

#28 i.sentinel1.gdargeocode: handle empty results
  src/imagery/i.sentinel1.gdargeocode/i.sentinel1.gdargeocode.py
Labels: bug

#30 remove metadata from download when using scenes option
  src/imagery/i.asf.download/i.asf.download.py
Labels: bug

#32 i.sentinel1.gdargeocode: Handle multi geometries and better check for polygons in AOI
  src/imagery/i.asf.download/i.asf.download.py
  src/imagery/i.sentinel1.gdargeocode/i.sentinel1.gdargeocode.py
Labels: bug

#36 i.sentinel1.pyrosargeocode: feed DEM path as str to pyrosar
  src/imagery/i.sentinel1.pyrosargeocode/i.sentinel1.pyrosargeocode.py
Labels: bug

#37 t.import.hrsi: document batch_size, cleanup
  src/temporal/t.import.hrsi/t.import.hrsi.html
Labels: bug, documentation
